// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcEUhp_HHwP5wWftKTOi-eL9xPn-QFvDg',
    appId: '1:970428444550:web:c923f45b9be3753e330607',
    messagingSenderId: '970428444550',
    projectId: 'chat-b34bb',
    authDomain: 'chat-b34bb.firebaseapp.com',
    storageBucket: 'chat-b34bb.firebasestorage.app',
    measurementId: 'G-KZB2Z9XSZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0j8ct-u60f6LZjEZdowowwWcz1Go4LS8',
    appId: '1:970428444550:android:468a8ebfe6e5623a330607',
    messagingSenderId: '970428444550',
    projectId: 'chat-b34bb',
    storageBucket: 'chat-b34bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJQWXiBkbEGEUe-cspJ46_04-R-leTAE',
    appId: '1:970428444550:ios:5ae84a2e6a723106330607',
    messagingSenderId: '970428444550',
    projectId: 'chat-b34bb',
    storageBucket: 'chat-b34bb.firebasestorage.app',
    androidClientId: '970428444550-hcikla6tfp2jeoq694fp6ee0evvs8g7q.apps.googleusercontent.com',
    iosClientId: '970428444550-pobrae6oqltmlbgoerbt9jbvhcts37dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJQWXiBkbEGEUe-cspJ46_04-R-leTAE',
    appId: '1:970428444550:ios:5ae84a2e6a723106330607',
    messagingSenderId: '970428444550',
    projectId: 'chat-b34bb',
    storageBucket: 'chat-b34bb.firebasestorage.app',
    androidClientId: '970428444550-hcikla6tfp2jeoq694fp6ee0evvs8g7q.apps.googleusercontent.com',
    iosClientId: '970428444550-pobrae6oqltmlbgoerbt9jbvhcts37dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

}